### ISSUE TITLE
Migrate from Boot to Clojure's command line tooling

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal-docs#105]
Clojure's tooling continues to advance and with the introduction of [tools.deps.alpha](https://github.com/clojure/tools.deps.alpha) we don't need separate tooling to drive the samples in the guides. This issue proposes updating the following guides to use tools.deps.alpha:

1. [Hello World](http://pedestal.io/guides/hello-world)
2. [Hello World, With Parameters](http://pedestal.io/guides/hello-world-query-parameters)
3. [Hello World, With Content Types](http://pedestal.io/guides/hello-world-content-types)
4. [Your First API](http://pedestal.io/guides/your-first-api)
5. [Using Pedestal with Component](http://pedestal.io/guides/pedestal-with-component)

The [Contributing](https://github.com/pedestal/pedestal-docs/blob/master/CONTRIBUTING.md) doc should also be updated to include this guidance when developing an interactive guide.

We could also drop the dependency on boot for [indexing the samples](https://github.com/pedestal/pedestal-docs#only-needed-when-pedestal-changes).

**Comment by ddeaguiar** [comment]
@mtnygard the deps across the guides need to be updated. I figured it would be worth doing this in the process.

**Comment by comnik** [comment]
FWIW I've started doing this here: https://github.com/comnik/pedestal-docs/commits/master
Will report back once everything is confirmed working.

**Comment by ddeaguiar** [comment]
Changes landed on `master`.
