### ISSUE TITLE
Unclear documentation sorrounding use of :io.pedestal.http.jetty/container-options

### ISSUE THREAD

**Issue by asilverman** [pedestal/pedestal-docs#127]
I would like to be able to learn how to configure my pedestal app using the :io.pedestal.http.jetty/container-options map, however I am confused how do these configurations conflict with :io.pedestal.http/container-options and how do these configurations affect the behavior of my pedestal application.

**Comment by ohpauleez** [comment]
I'm sure Dan will chime in with some helpful context and links, but I wanted to provide a quick response to get you rolling.

There is only one set of container options, `:io.pedestal.http/container-options`, and based on your container, different settings can placed in there (eg: not all containers have the same settings for `container-options`.  The options in here are always container-specfic).

If you're using an `:io.pedestal.http/type` of `:jetty` then the container options will be applied to the jetty container (and will be jetty-specific settings).

**Comment by ddeaguiar** [comment]
Thanks @ohpauleez. There is currently one jetty-specific container option that we support and it's `io.pedestal.http.jetty/http-configuration` which is expected to be instance of `org.eclipse.jetty.server.HttpConfiguration`. This makes it easier for users to take full control over configuring the http server. If you specify that option, it's used _instead_ of any other container options you pass in.

The other supported options are container-agnostic and can be found in the [`service.clj`](https://github.com/pedestal/pedestal/blob/0.5.7/service-template/src/leiningen/new/pedestal_service/service.clj#L73-L82) generated by the `lein` pedestal-service template.

I plan to update the docs accordingly.

**Comment by ddeaguiar** [comment]
I've pushed [documentation](http://pedestal.io/reference/jetty) for the Jetty options. I misspoke when I said there was only one jetty-specific container option. There are a number of them, we just namespace the `http-configuration` option.
