### ISSUE TITLE
Using map in chain/enqueue crashes server

### ISSUE THREAD

**Issue by ujjwalt** [pedestal/pedestal-docs#137]
https://github.com/pedestal/pedestal-docs/blob/6bf8eaf503b49cc4c64dfad486b6e6b59d3d21ba/content/guides/what-is-an-interceptor-src/src/intc/service.clj#L42

This should instead be
```clj
(chain/enqueue context [(io.pedestal.interceptor/interceptor nxt)]))
```

**Comment by ddeaguiar** [comment]
A similar issue was opened on the pedestal repository (https://github.com/pedestal/pedestal/issues/649).

**Comment by ddeaguiar** [comment]
Guide updated.
