### ISSUE TITLE
Add documentation on how to work on Pedestal development

### ISSUE THREAD

**Issue by grzm** [pedestal/pedestal-docs#29]
I've found getting started working on Pedestal itself a little bit of a chore. Part of this I believe is due to my inexperience working on libraries, but then again, we want to keep the barrier of entry to contributions as low as possible. Someone who doesn't have a lot of experience but wants to contribute should find it easy to do so.

There are two aspects to this:
 1. Working with unreleased versions of Pedestal in your own projects. Often you find a bug in your project. A fix might be committed but not released. How do you easily test the fix in your project? I use Leiningen in my own projects. Currently I use the Reloaded workflow and lein-test-refresh, both of which have issues when using lein checkouts for Pedestal due to dependencies that can't be loaded. To work around this I use lein install to put SNAPSHOT in my local maven repo. Due to how the Pedestal project is organized, I need to run lein install in each subdirectory. If I'm working with a bunch of different changes independently, this is tedious and error prone. Yes, I should script this. Should we provide a script that does this? Perhaps there's a script that does this already? Maybe some feature of Leiningen I don't know about? How are others handling this? What are some of the best practices?
 2. What are the best practices for developing on Pedestal itself, independent of a particular project? What workflow do the maintainers use? Is there a way of testing the entire project (not just a single subproject)? Are there any automated tools that are useful? For my own projects I've found lein test-refresh useful. Should we consider adding that to the project files for testing?

**Comment by ohpauleez** [comment]
I'm sure we'll have a "Contribute" doc, but for now, you should use the [Contributing README section](https://github.com/pedestal/pedestal#contributing).

From the top-level of Pedestal, you can run `lein sub install`, which will install a snapshot of all the Pedestal libraries.  You can also run `lein sub test` to run *all* the tests, but I rarely do this (usually only before a commit.  The majority of the tests are in `service`, so you can just run `lein test` within that directory.

So the steps would be:

1. Fork the repo
2. Create a branch for you feature/bugfix
3. From the top-level of the repo `lein sub install`
4. Make your changes and add tests under the `service` project
5. Run `lein test` under the `service` project as needed, and make small commits as you go
6. When you're done, `lein sub test` from the top-level directory
7. Submit a PR

**Comment by grzm** [comment]
Thanks for the pointers. I also see that this is included in the current pedestal-docs https://github.com/pedestal/pedestal-docs/blob/master/content/community/index.adoc

I know I looked at the local pedestal-docs site I have running. I'm feeling really daft.

**Comment by ohpauleez** [comment]
No worries!

**Comment by mtnygard** [comment]
I'd like to keep this issue open. It will serve as a reminder to bring that information over into the new structure.

**Comment by mtnygard** [comment]
I've addressed this in 3f13436
