### ISSUE TITLE
Typo in Your First API Guide

### ISSUE THREAD

**Issue by gpellis** [pedestal/pedestal-docs#39]
With this new helper we can try out a lot of requests from the REPL.
Don't forget to reload the main namespace in the REPL (`(require main :reload)`)
and restart the server (`(main/restart)`) before you do.

Main needs to be quoted, `(require 'main :reload)`. Also, seems like the double parens could be misinterpreted.

**Comment by mtnygard** [comment]
Thanks for catching that!
