### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gpellis** [pedestal/pedestal-docs#41]
The `Developing at the REPL` link on the guides page, under the interactive development section, is broken.  It looks like it is supposed to point to #37, but that page isn't merged yet.

**Comment by mtnygard** [comment]
Thanks for the report. I'm going to merge #37 to fix the broken link, then @ohpauleez and I will work on the content improvements that are discussed in that PR.

**Comment by mtnygard** [comment]
Latest build is up on http://pedestal.io and the link works.

**Comment by christianromney** [comment]
Been swamped, sorry guys. Glad to see it's getting some traction though.
