### ISSUE TITLE
references from the 70's should be linked

### ISSUE THREAD

**Issue by jeffmad** [pedestal/pedestal-docs#51]
I am going through the tutorials and am enjoying them.  I am sure it will help new people get comfortable with Pedestal. 

On
http://pedestal.io/guides/hello-world-query-parameters

Pedestal **ginsus** that up into a map of parameters for you

As much as that made me chuckle because I was regularly held captive to that commercial as a child, many readers are too young to get the reference or came from outside the US and will not find an entry for the verb "ginsu" at dictionary.com.   I recommend adding a link https://www.youtube.com/watch?v=abLB7aTmnE4  to the original commercial or choosing another word.   Yeah, 70s,  Freedom Rock dude, turn it up!

**Comment by mtnygard** [comment]
This may be my favorite issue ever filed. Thanks!
