### ISSUE TITLE
Stopping and restarting server in the repl

### ISSUE THREAD

**Issue by dfcarpenter** [pedestal/pedestal-docs#52]
It's not clear following the guide that when running the server in the repl that one should use something like this `(def my-server (hello/start))` in order to start the server and then something like `(io.pedestal.http/stop my-server)` to stop the server. I was confused in the second part of the guide concerning query parameters when it was asked to restart the server (faultily assuming I could just run (hello/start) again) but on attempting this the error appeared  `java.net.BindException: Address already in use` . I had to kill the REPL and restart in order to proceed. On Slack several helpful users (@mavbozo, and @ddeaguiar in the pedestal channel in clojurians pointed out some solutions)

1. Adding `::http/join?` false to the http/create-server function
2. the (def my-server option)
3. `(alter-var-root #'my-server io.pedestal.http/stop)`

**Comment by ohpauleez** [comment]
Hi @dfcarpenter -- thanks for reaching out with the issue and raising your confusion.

In the [Starting and Stopping](https://github.com/pedestal/pedestal-docs/blob/master/content/guides/developing-at-the-repl.adoc#starting-and-stopping-the-http-server) section, the guide suggests against that practice.  Instead, it's advised that you just re-require your source files (the changes are automatically picked up by the running dev server).

```
At the REPL, invoke the run-dev function to start the server:

pedrepl.server> (def serv (run-dev))

Now fire up a browser and navigate to http://localhost:8080 to see the default, "Hello, World!" message.
Within service.clj, update the home-page handler to respond with "Hello Pedestal User". Re-require/reload the service.clj and when you reload http://localhost:8080 you’ll see the change immediately.

In dev-mode, you should never have to restart the server - changes are picked up as soon as they’re required/reloaded.
```

It seems like the guide isn't fully self-consistent is suggesting this practice, sorry about that!  If you find yourself needing to stop/restart the service, please share your workflow/usecase so we can address it better in the docs.  Thanks!

**Comment by ohpauleez** [comment]
@dfcarpenter - once the concepts make sense to you, you can also use the template:

`lein new pedestal-service myservice`

**Comment by ddeaguiar** [comment]
@ohpauleez I had created PR #53 which I think is consistent with the message in the [Starting and Stopping](https://github.com/pedestal/pedestal-docs/blob/master/content/guides/developing-at-the-repl.adoc#starting-and-stopping-the-http-server) section of the repl guide. If you think otherwise I'll close it.

**Comment by ddeaguiar** [comment]
That PR only updates one of the _Hello World_ examples, though.

**Comment by ddeaguiar** [comment]
Interactive development is brought up in the [Your First API](http://pedestal.io/guides/your-first-api#_interactive_development) guide. The intended user action in the [Hello World, With Parameters](http://pedestal.io/guides/hello-world-query-parameters) guide is that the repl is killed.
