### ISSUE TITLE
Document features and limitations of the routers

### ISSUE THREAD

**Issue by mtnygard** [pedestal/pedestal-docs#61]
Especially the prefix-tree router, since it's the default. See https://github.com/pedestal/pedestal/pull/330.

**Comment by DjebbZ** [comment]
Bumping the issue. Yes please, it happens that I need to use the prefix-tree router now. I'll try searching the docs in the meantime.

**Comment by ddeaguiar** [comment]
I think this is adequately covered in the current docs for the [built-in routers](http://pedestal.io/reference/using-the-builtin-routers) and [Prefix Tree Router](http://pedestal.io/reference/prefix-tree-router).
