### ISSUE TITLE
Bug in pedestal.io website guide

### ISSUE THREAD

**Issue by oasalonen** [pedestal/pedestal-docs#65]
In http://pedestal.io/guides/hello-world-content-types#_the_whole_shebang see hello.clj defn greeting-for.

The line
(unmentionables nm) nm
should be
(unmentionables nm) nil

as shown in an earlier example of the guide (http://pedestal.io/guides/hello-world-query-parameters#_conditional_responses)

**Comment by mtnygard** [comment]
Thank you!
