### ISSUE TITLE
404 Not Found on request to created list in "Your First API" guide

### ISSUE THREAD

**Issue by agodde** [pedestal/pedestal-docs#74]
I've copied "the whole shebang" from the end of the [Your First API guide](http://pedestal.io/guides/your-first-api) and ran the code with leiningen using the dependencies specified at the beginning of the chapter. POSTing a new list with curl (curl -i -X POST localhost:8890/todo?name=mylist) results in a 201 response including a location header. However, trying to then query the new URI (curl -i localhost:8890/id) results in a 404 error.

I've tried to narrow down the source of the error and found that the key ":params" used in the function list-view is not populated with the list-id. The ":path-params" key, however, contains the required value.
Using this to get the list from the database, fails as well, though.
Accessing the database from the REPL (get @database "id") returns nil, although the keys in the database are the list-ids as strings. I've double checked that the keys in the database really are strings, but so far I had no success to get a value from that map.

Maybe I'm missing something obvious here, since I'm fairly new to Clojure. But from my understanding, at least the manual (get ...) to the database should work...

Thanks for your help!

**Comment by mtnygard** [comment]
This was kindly fixed by @saicheong in pull request #76
