### ISSUE TITLE
Smooth the learning curve of "Hello World, With Content Types"

### ISSUE THREAD

**Issue by smahood** [pedestal/pedestal-docs#77]
During the refactor of the "Hello World, With Content Types", the usage of `cond->` seems like a much more significant jump in understanding of Clojure than the rest of the content. I think it would make it much easier to understand if there was some sort of intermediate step to help smooth over what I expect will be a stumbling block for many, especially if they are new to Clojure.

**Comment by mtnygard** [comment]
Thanks for the feedback. That's a good idea.
