### ISSUE TITLE
Confusing paragraph about :form-params and keyword-params

### ISSUE THREAD

**Issue by terjesb** [pedestal/pedestal-docs#87]
#57 cleaned up some confusion about keywordizing in :params (not by default) and :form-params (yes by default, when possible).

Just discovered that http://pedestal.io/reference/parameters still has a confusing paragraph around this:

> One catch to note has to do with form parameters from an HTTP POST request. Because form fields can be named just about anything, the keys in these maps aren’t automatically converted to keywords. If you want them to be keywordized, you should make sure to have the keyword-params interceptor on the applicable route.

This is confusing as 1) :form-params (and :query-params) _are_ now by default converted to keywords, when possible and 2) adding keyword-params would _also_ keywordize :params, which by default are not keywordized.

Maybe simply remove this paragraph to avoid further confusion?

**Comment by ddeaguiar** [comment]
Added clarifications to the Parameters reference.
