### ISSUE TITLE
Terse routing describes verb map incorrectly.

### ISSUE THREAD

**Issue by mtnygard** [pedestal/pedestal-docs#91]
The "Quick Reference" says "The value of each key is either a handler function or a list of interceptors." That doesn't seem to work any more. The correct syntax is more like:

```clojure
{:verb ^{:interceptors [interceptor-1 interceptor-2]} handler}
```

when only one verb uses the handler, or:

```clojure
{:verb ^{:interceptors [interceptor-1 interceptor-2]} [:route-name handler]}
```

when the same handler is used by more than one verb.

**Comment by ohpauleez** [comment]
Hmm, this seems interesting to me.  I'd like to dig into Pedestal to understand if this is the case and make sure we capture it in the [route test](https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/route_test.clj#L186)

**Comment by mtnygard** [comment]
I went to the route test in order to find the correct syntax. Just working from the docs (that date way back to 0.1 or something) I wasn't able to find a solution that worked for our user.

**Comment by mtnygard** [comment]
Meaning that I have high confidence in the test, much less in the docs. :-)

**Comment by ddeaguiar** [comment]
@mtnygard I don't understand this issue. The text you are referring to in the issue description pertains to the Terse Syntax [section](http://pedestal.io/reference/routing-quick-reference#_terse_syntax) of the docs. Neither the syntax there or in the issue description are correct terse route syntax. The value associated with the key needs to implement `ExpandableVerbAction` and as of Pedestal 0.5.2 the implementation of that protocol is limited to symbols, lists and vectors.

The tests found in the [route test](https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/route_test.clj#L186) referenced by @ohpauleez leverage the `defhandler` interceptor to create handlers. If a function is referenced instead, it or the entire terse route vector needs to be quoted.

The following samples are correct:

```
(def routes
  ;; interceptors apply to both "/" and "/about"
  [[["/" {:get `home-page}
     ^:interceptors [(body-params/body-params) http/html-body]
     ["/about" {:get `about-page}]]]])

(def routes
  ;; interceptors apply to "/" only
  [[["/" {:get [:home ^:interceptors [(body-params/body-params) http/html-body] `home-page]}
     ["/about" {:get `about-page}]]]])
```
I could be misunderstanding this issue, though. I find the terse route syntax to be confusing and I typically need to go back to some samples to refresh my memory.

**Comment by mtnygard** [comment]
IIRC, the problem was that the docs suggested you could use a vector of interceptors, but a vector was being interpreted as (possible) route name.

Probably best to regard this issue as really saying “make the docs & samples all match the implementation.”

**Comment by ddeaguiar** [comment]
Ok, the example I included in my previous comment demonstrates the different ways interceptors can be specified. I'll work on clarifying the docs.

**Comment by ddeaguiar** [comment]
Closing this as the PR with doc clarifications has been merged.
