### ISSUE TITLE
hello-world **java.net.BindException: Address already in use** on server restart

### ISSUE THREAD

**Issue by kentoj** [pedestal/pedestal-docs#96]
When restarting the server from the **boot** repl I am getting a `java.net.BindException: Address already in use` exception on every restart. I end up having to exit boot and get back in. 

I am using Ctrl + C to exit the Jetty web server.

Versions:
```bash
$ boot -V
#http://boot-clj.com
#Fri Dec 15 15:13:12 MST 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.8.0
BOOT_VERSION=2.7.2
```

**Comment by ddeaguiar** [comment]
I'm in the process of updating the guides and I will make this clearer. I'll close this issue once that is done. Sorry for the confusion!

**Comment by fabiotc** [comment]
Maybe adding a command like this: `kill $(lsof -t -i:8890)` could be useful.

**Comment by ddeaguiar** [comment]
The guide should be clearer about this now.
